In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('data.csv', decimal = ',')

In [4]:
df.describe()

,Unnamed: 0,ID,Age,Overall,Potential,Special,International Reputation,Weak Foot,Skill Moves,Jersey Number,...,Penalties,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes
count,18207.000000,18207.000000,18207.000000,18207.000000,18207.000000,18207.000000,18159.000000,18159.000000,18159.000000,18147.000000,...,18159.000000,18159.000000,18159.000000,18159.000000,18159.000000,18159.000000,18159.000000,18159.000000,18159.000000,18159.000000
mean,9103.000000,214298.338606,25.122206,66.238699,71.307299,1597.809908,1.113222,2.947299,2.361308,19.546096,...,48.548598,58.648274,47.281623,47.697836,45.661435,16.616223,16.391596,16.232061,16.388898,16.710887
std,5256.052511,29965.244204,4.669943,6.908930,6.136496,272.586016,0.394031,0.660456,0.756164,15.947765,...,15.704053,11.436133,19.904397,21.664004,21.289135,17.695349,16.906900,16.502864,17.034669,17.955119
min,0.000000,16.000000,16.000000,46.000000,48.000000,731.000000,1.000000,1.000000,1.000000,1.000000,...,5.000000,3.000000,3.000000,2.000000,3.000000,1.000000,1.000000,1.000000,1.000000,1.000000
25%,4551.500000,200315.500000,21.000000,62.000000,67.000000,1457.000000,1.000000,3.000000,2.000000,8.000000,...,39.000000,51.000000,30.000000,27.000000,24.000000,8.000000,8.000000,8.000000,8.000000,8.000000
50%,9103.000000,221759.000000,25.000000,66.000000,71.000000,1635.000000,1.000000,3.000000,2.000000,17.000000,...,49.000000,60.000000,53.000000,55.000000,52.000000,11.000000,11.000000,11.000000,11.000000,11.000000
75%,13654.500000,236529.500000,28.000000,71.000000,75.000000,1787.000000,1.000000,3.000000,3.000000,26.000000,...,60.000000,67.000000,64.000000,66.000000,64.000000,14.000000,14.000000,14.000000,14.000000,14.000000
max,18206.000000,246620.000000,45.000000,94.000000,95.000000,2346.000000,5.000000,5.000000,5.000000,99.000000,...,92.000000,96.000000,94.000000,93.000000,91.000000,90.000000,92.000000,91.000000,90.000000,94.000000

In [6]:
df['Finishing']

0        95.0
1        94.0
2        87.0
3        13.0
4        82.0
5        84.0
6        72.0
7        93.0
8        60.0
9        11.0
10       91.0
11       76.0
12       42.0
13       76.0
14       65.0
15       84.0
16       94.0
17       90.0
18       14.0
19       14.0
20       67.0
21       89.0
22       13.0
23       93.0
24       33.0
25       88.0
26       90.0
27       59.0
28       83.0
29       77.0
         ...
18177    53.0
18178     7.0
18179    22.0
18180    15.0
18181    46.0
18182    33.0
18183    12.0
18184    24.0
18185    34.0
18186    29.0
18187    40.0
18188    38.0
18189    48.0
18190    32.0
18191    26.0
18192    36.0
18193    25.0
18194     6.0
18195    29.0
18196    28.0
18197    44.0
18198     8.0
18199    31.0
18200    47.0
18201    23.0
18202    38.0
18203    52.0
18204    40.0
18205    50.0
18206    34.0
Name: Finishing, Length: 18207, dtype: float64

In [7]:
df['Flag']

0         https://cdn.sofifa.org/flags/52.png
1         https://cdn.sofifa.org/flags/38.png
2         https://cdn.sofifa.org/flags/54.png
3         https://cdn.sofifa.org/flags/45.png
4          https://cdn.sofifa.org/flags/7.png
5          https://cdn.sofifa.org/flags/7.png
6         https://cdn.sofifa.org/flags/10.png
7         https://cdn.sofifa.org/flags/60.png
8         https://cdn.sofifa.org/flags/45.png
9         https://cdn.sofifa.org/flags/44.png
10        https://cdn.sofifa.org/flags/37.png
11        https://cdn.sofifa.org/flags/21.png
12        https://cdn.sofifa.org/flags/60.png
13        https://cdn.sofifa.org/flags/45.png
14        https://cdn.sofifa.org/flags/18.png
15        https://cdn.sofifa.org/flags/52.png
16        https://cdn.sofifa.org/flags/14.png
17        https://cdn.sofifa.org/flags/18.png
18        https://cdn.sofifa.org/flags/21.png
19         https://cdn.sofifa.org/flags/7.png
20        https://cdn.sofifa.org/flags/45.png
21        https://cdn.sofifa.org/flags/60.png
22        https://cdn.sofifa.org/flags/21.png
23        https://cdn.sofifa.org/flags/52.png
24        https://cdn.sofifa.org/flags/27.png
25        https://cdn.sofifa.org/flags/18.png
26       https://cdn.sofifa.org/flags/111.png
27        https://cdn.sofifa.org/flags/54.png
28        https://cdn.sofifa.org/flags/56.png
29        https://cdn.sofifa.org/flags/27.png
                         ...
18177     https://cdn.sofifa.org/flags/25.png
18178     https://cdn.sofifa.org/flags/46.png
18179     https://cdn.sofifa.org/flags/14.png
18180     https://cdn.sofifa.org/flags/42.png
18181     https://cdn.sofifa.org/flags/25.png
18182     https://cdn.sofifa.org/flags/56.png
18183     https://cdn.sofifa.org/flags/14.png
18184     https://cdn.sofifa.org/flags/14.png
18185     https://cdn.sofifa.org/flags/25.png
18186    https://cdn.sofifa.org/flags/155.png
18187     https://cdn.sofifa.org/flags/21.png
18188     https://cdn.sofifa.org/flags/50.png
18189     https://cdn.sofifa.org/flags/21.png
18190     https://cdn.sofifa.org/flags/14.png
18191     https://cdn.sofifa.org/flags/14.png
18192     https://cdn.sofifa.org/flags/14.png
18193     https://cdn.sofifa.org/flags/55.png
18194     https://cdn.sofifa.org/flags/27.png
18195     https://cdn.sofifa.org/flags/25.png
18196    https://cdn.sofifa.org/flags/163.png
18197     https://cdn.sofifa.org/flags/25.png
18198     https://cdn.sofifa.org/flags/14.png
18199     https://cdn.sofifa.org/flags/70.png
18200     https://cdn.sofifa.org/flags/42.png
18201     https://cdn.sofifa.org/flags/25.png
18202     https://cdn.sofifa.org/flags/14.png
18203     https://cdn.sofifa.org/flags/46.png
18204     https://cdn.sofifa.org/flags/14.png
18205     https://cdn.sofifa.org/flags/14.png
18206     https://cdn.sofifa.org/flags/14.png
Name: Flag, Length: 18207, dtype: object

In [8]:
df['Special']

0        2202
1        2228
2        2143
3        1471
4        2281
5        2142
6        2280
7        2346
8        2201
9        1331
10       2152
11       2190
12       1946
13       2115
14       2189
15       2092
16       2165
17       2246
18       1328
19       1311
20       2065
21       2161
22       1473
23       2107
24       1841
25       2118
26       2146
27       2170
28       2171
29       2017
         ...
18177    1178
18178     738
18179    1166
18180     987
18181    1296
18182    1311
18183     774
18184    1368
18185    1315
18186    1389
18187    1366
18188    1297
18189    1290
18190    1285
18191    1250
18192    1325
18193    1191
18194     731
18195    1325
18196    1333
18197    1362
18198     792
18199    1303
18200    1203
18201    1098
18202    1307
18203    1098
18204    1189
18205    1228
18206    1321
Name: Special, Length: 18207, dtype: int64

In [9]:
df.isnull().sum().sum()

76984

In [10]:
df.isnull().sum()

Unnamed: 0                      0
ID                              0
Name                            0
Age                             0
Photo                           0
Nationality                     0
Flag                            0
Overall                         0
Potential                       0
Club                          241
Club Logo                       0
Value                           0
Wage                            0
Special                         0
Preferred Foot                 48
International Reputation       48
Weak Foot                      48
Skill Moves                    48
Work Rate                      48
Body Type                      48
Real Face                      48
Position                       60
Jersey Number                  60
Joined                       1553
Loaned From                 16943
Contract Valid Until          289
Height                         48
Weight                         48
LS                           2085
ST                           2085
                            ...
Dribbling                      48
Curve                          48
FKAccuracy                     48
LongPassing                    48
BallControl                    48
Acceleration                   48
SprintSpeed                    48
Agility                        48
Reactions                      48
Balance                        48
ShotPower                      48
Jumping                        48
Stamina                        48
Strength                       48
LongShots                      48
Aggression                     48
Interceptions                  48
Positioning                    48
Vision                         48
Penalties                      48
Composure                      48
Marking                        48
StandingTackle                 48
SlidingTackle                  48
GKDiving                       48
GKHandling                     48
GKKicking                      48
GKPositioning                  48
GKReflexes                     48
Release Clause               1564
Length: 89, dtype: int64

In [11]:
df['Body Type']

0                      Messi
1                 C. Ronaldo
2                     Neymar
3                       Lean
4                     Normal
5                     Normal
6                       Lean
7                     Normal
8                     Normal
9                     Normal
10                    Normal
11                    Normal
12                      Lean
13                    Normal
14                      Lean
15                    Normal
16                    Normal
17                      Lean
18                    Normal
19                  Courtois
20                      Lean
21                      Lean
22                    Normal
23                    Stocky
24                    Normal
25                      Lean
26       PLAYER_BODY_TYPE_25
27                    Normal
28                    Normal
29                    Normal
                ...
18177                   Lean
18178                   Lean
18179                   Lean
18180                   Lean
18181                   Lean
18182                   Lean
18183                 Normal
18184                 Normal
18185                 Normal
18186                 Normal
18187                   Lean
18188                   Lean
18189                   Lean
18190                 Normal
18191                   Lean
18192                   Lean
18193                   Lean
18194                 Normal
18195                 Normal
18196                   Lean
18197                 Normal
18198                   Lean
18199                   Lean
18200                   Lean
18201                   Lean
18202                   Lean
18203                 Normal
18204                 Normal
18205                   Lean
18206                   Lean
Name: Body Type, Length: 18207, dtype: object

In [12]:
df['Real Face']

0        Yes
1        Yes
2        Yes
3        Yes
4        Yes
5        Yes
6        Yes
7        Yes
8        Yes
9        Yes
10       Yes
11       Yes
12       Yes
13       Yes
14       Yes
15       Yes
16       Yes
17       Yes
18       Yes
19       Yes
20       Yes
21       Yes
22       Yes
23       Yes
24       Yes
25       Yes
26       Yes
27       Yes
28       Yes
29       Yes
        ...
18177     No
18178     No
18179     No
18180     No
18181     No
18182     No
18183     No
18184     No
18185     No
18186     No
18187     No
18188     No
18189     No
18190     No
18191     No
18192     No
18193     No
18194     No
18195     No
18196     No
18197     No
18198     No
18199     No
18200     No
18201     No
18202     No
18203     No
18204     No
18205     No
18206     No
Name: Real Face, Length: 18207, dtype: object